name: wisc-prolonged-infection
channels:
  - conda-forge
  - bioconda
  - main
  - r
dependencies:
  - R
  - r-ggplot2
  - bioconductor-biostrings
  - r-tidyverse
  - r-plotrix
  - coreutils=9.1
  - sra-tools=2.10.1
